import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header, UpperHeader } from "./Components/header";
import Footer from "./Components/footer";
import { CartProvider } from "./context/CartContext"; // Import the CartProvider
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {/* <UpperHeader /> */}
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
           <Header />
          {children}
          <ToastContainer /> {/* Add ToastContainer */}

          <Footer />
        </CartProvider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
